server:
  port: 8080

camel:
  component:
    rabbitmq:
      hostname: localhost
      port: 5672
      username: guest
      password: guest

logging:
  level:
    root: INFO
    org.apache.camel: INFO
